### ISSUE TITLE
Deployment accessor for types are not polymorphic -> Compiler error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [franca/franca#101]
```
What steps will reproduce the problem?
1. Specify: for structs {IsLockable : Boolean (default:false);} in 
DeploySpec.fdepl
2. Specify: for arrays {IsLockable : Boolean (default:false);} in 
DeploySpec.fdepl

What is the expected output? What do you see instead?

In generated Java class public class DeploySpecInterfacePropertyAccessor
there should be two polymorphic methods:
public Boolean getIsLockable (FCompoundType obj)
public Boolean getIsLockable (FArrayType obj)

But what I get is:
public Boolean getIsLockable (EObject obj)
public Boolean getIsLockable (EObject obj)
This is a general problem, because accessors for all types always use EObject 
instead of the actual type. 

What version of the product are you using? On what operating system?
Franca 0.8.9

Please provide any additional information below.


```

Original issue reported on code.google.com by `Roman.St...@gmail.com` on 8 May 2014 at 7:11

**Comment by kbirken** [comment]
Meanwhile, there has been significant progress on this issue.

1. For Franca 0.9.2 we had a major rewrite of the PropertyAccessor generator. After this, the example from the description of this issue is now perfectly valid. You can find a test model which shows the valid possibilities for duplicate property names here:

https://github.com/franca/franca/blob/develop/tests/org.franca.deploymodel.dsl.tests/model/testcases/14-SpecDuplicatePropertyNames.fdepl

2. However, even with 0.9.2 or newer there are restrictions for some property combinations with the same name. The restrictions are due to colliding methods or enumerators in the Java code generated from the deployment specifications. With commit 349aada (on branch develop) we introduced a whole new set of validation rules which mark every combination as an error which would later lead to syntactic or semantic errors in the resulting Java code. See the following test model (in Xpect) to get an impression of the new checks:

https://github.com/franca/franca/blob/develop/tests/org.franca.deploymodel.dsl.tests/src/org/franca/deploymodel/dsl/tests/xpect/PropDeclClashValidationTest.fdepl.xt

The checks result from the following restrictions related to the generated Java code:
* property names for the same host must be unique
* property names for different hosts may be equal, iff none of the following conditions are true
  * the type of the property is an enumeration
  * the argument types of the getter-methods in the generated PropertyAccessor are not identical and do not belong to the same class hierarchy

The latter condition is hard to understand by looking at the model alone (the actual problem is due to static method overloading in Java). Thus, we tried to provide meaningful validation messages to give the user a hint how the situation could be improved.

3. We will update the deployment chapter in the User Guide soon to reflect the new validation rules.

**Comment by kbirken** [comment]
@klausuhl-intel FYI
