### ISSUE TITLE
The new "Integer" type is represented as UNDEFINED in FTypeRef

### ISSUE THREAD

**Issue by awarnke** [franca/franca#163]
switch ( typeRef.getPredefined() ) 
		    {
		        case INT8   : result = "int8_t"; break;
		        case INT16  : result = "int16_t"; break;
		        case INT32  : result = "int32_t"; break;
		        case INT64  : result = "int64_t"; break;
		        case UINT8  : result = "uint8_t"; break;
		        case UINT16 : result = "uint16_t"; break;
		        case UINT32 : result = "uint32_t"; break;
		        case UINT64 : result = "uint64_t"; break;
		        case STRING : result = "char"; break;
		        case BOOLEAN: result = "int"; break;
		        case FLOAT  : result = "float"; break;
		        case DOUBLE : result = "double"; break;
		        case BYTE_BUFFER : result = "unsigned char"; break;
		        case UNDEFINED : result = "int64_t"; break;

The last case statement creates the output for an "Integer" type. The enumerator-name looks like "not final" ;-)

cu
Andreas

**Comment by kbirken** [comment]
I am not sure if I understand this issue correctly. You refer to FTypeRef, so I assume this is a question about the model API. An FTypeRef object has three mutually exclusive attributes:

* predefined: This is used in your code example. It covers all the specific integer types, strings, booleans, float, double, byte buffers.
* interval: This covers the ranged integer types as usable with the keyword "Integer". 
* derived: This covers all the user-defined types, like arrays, structs etc.

Having said this, can you specify the problem you are referring to? It seems your code example is from a C code generator (this is not a piece of code from Franca).

**Comment by awarnke** [comment]
Hello Klaus,
thank you for asking and yes, I refer to the FTypeRef - the getPredefined() returns an enumeration of type public final enum org.franca.core.franca.FBasicTypeId


This Enum defines some enumeration values, e.g.

// Field descriptor #8 Lorg/franca/core/franca/FBasicTypeId;
  public static final enum org.franca.core.franca.FBasicTypeId UNDEFINED;
  
  // Field descriptor #8 Lorg/franca/core/franca/FBasicTypeId;
  public static final enum org.franca.core.franca.FBasicTypeId INT8;
  
  // Field descriptor #8 Lorg/franca/core/franca/FBasicTypeId;
  public static final enum org.franca.core.franca.FBasicTypeId UINT8;
  
  // Field descriptor #8 Lorg/franca/core/franca/FBasicTypeId;
  public static final enum org.franca.core.franca.FBasicTypeId INT16;

in this Enum, no representation for "Integer" exists. UNDEFINED is used instead.

Do you see my problem? 
The piece is indeed from a c code generator - and it works - but using "UNDEFINED" for generating "Integer" is weired.
Andreas

**Comment by kbirken** [comment]
@awarnke yes, Integer is not a member of FBasicTypeId because we do not regard Integer as a predefined type - it can be specified further by attaching a range. In order to detect Integer types properly, your code should be extended like this

```Java
if (typeRef.getInterval()!=null) {
  // this is an "Integer", use typeRef.getInterval() to check for a range definition
  // ...
} else if (typeRef.getDerived()!=null {
  // this is a user-defined type (struct, union, ...)
  // ...
} else {
  switch (typeRef.getPredefined()) {
      // continue as usual
  }
}
```

Got it? There is an alternative, if you do not want to handle Integer types at all. There is a framework class IntegerTypeConverter [1] which allows to replace all Integer types in your model by a proper predefined scalar type, taking into account the ranges specified by the user. The class also supports the other way round. So you could use IntegerTypeConverter as a preprocessing step before running your generator. Then you do not have to handle Integer-types at all :-)

The User Guide is still very quiet about this helper class, but there is some Javadoc which gives you more information and you can also check issue 18.

[1] https://github.com/franca/franca/blob/develop/plugins/org.franca.core/src/org/franca/core/utils/IntegerTypeConverter.xtend

**Comment by awarnke** [comment]
Hello Klaus,
Thank you for the hint!
removeRangedIntegers() looks good!
cu
Andreas

**Comment by kbirken** [comment]
This issue seems to be a question which is already answered.
