### ISSUE TITLE
Protobuf dependency errors

### ISSUE THREAD

**Issue by nagavijays** [franca/franca#200]
Question:
I tried to setup franca in developer machine by checking it from github and followed the guide https://github.com/franca/franca/wiki/Franca-Install-Sources-For-Dev. 

I am using Eclipse Mars 2 and Java 7.  I am getting protobuf dependency issues in "org.franca.connectors.protobuf" project. I couldn't find any orbit repository with the specified version. Could you please clarify?

**Comment by kbirken** [comment]
If you do not need to transform models from Google Protobuf to Franca IDL, just disable the org.franca.connectors.protobuf project in your workspace.

Otherwise you can use Franca's [target platform definition](https://github.com/franca/franca/blob/master/releng/org.franca.targetplatform/franca-luna.target) to set a target platform which contains the dependency to the **com.google.eclipse.protobuf.feature.group** package.

**Comment by kbirken** [comment]
One more remark: The protobuf dependency is not available in the Orbit repository.

Could you solve the problem? May the issue be closed now?

**Comment by kbirken** [comment]
No feedback, seems to be solved. Closing the issue.
