### ISSUE TITLE
Yamaica: undocumented naming rule enforced?

### ISSUE THREAD

**Issue by moltob** [franca/franca#213]
Please let me know, if this is not the right place for this question.

Yamaica enforces a naming convention in deployment specifications "Properties must begin with an uppercase character". This is not part of the grammar and seems a bit arbitrary at first sight. Did I miss something? What is the reason for this rule?

Thanks for the background.

**Comment by kbirken** [comment]
This is a validation rule that comes with the Franca deployment models, it is not something added by Yamaica (there could be specific validation rules by tools based on Franca, but here this is not the case).

This is a rule from the early days of Franca deployment and indeed seems a bit arbitrary. However, the property names have to be first-char-uppercase in the Java code of the generated PropertyAccessor API. Therefore, it is useful if the property name is identical to the generated Java API. 

Moreover, because the deployment definitions might become quite complex, every implicit rule which provides some guidance helps - thus the above rule is beneficial.
