### ISSUE TITLE
Franca support for fine-granular data type definitions (bit groups)

### ISSUE THREAD

**Issue by ck-euros** [franca/franca#235]
In the fields of communication protocols or embedded systems many interfaces operate with a data granularity of bits rather than bytes. 

For example, automotive CAN messages may comprise different measuring values of different bit size, tightly packed (sometimes overlapping byte boundaries), in order to use the bus efficiently.
A receiver of such CAN message may want to parse the incoming byte array in order to extract the 6-bit value representing battery voltage, the 3-bit value representing the current gear, ect..

Another example are special function registers in microcontrollers or FPGAs. A 32-bit register may comprise groups of bits representing different settings.
Since many users prefer configuration over programming, tool developers may want to discribe such interfaces in Franca and generate the GUI for their configuration as well as the target code for their initialization/modification.

Currently, I use deployment models for the definition of bit masks in string format, e.g. "0x0007FFFE". Later the generated code can utilize those masks to extract the relevant bits.
However, I consider my approach as a workaround because it requires implicitely that users of the interface definition recognize bit masks as such and apply them as intended, e.g. use BitMask_STDID on data X for extraction of the value of STDID.

Is there a Franca-only solution, i.e. one that works out-of-the-box without the necessity that counterparts know about my bit mask concept?

Thank you very much in advance!

**Comment by kbirken** [comment]
Usually, Franca IDL is applied more as a specification language than a technical "implementation" language. However, here are some remarks regarding your challenge.

If you want to stick with the bitmask approach (either in fidl or in fdepl), you could improve it a little bit by using UInt64 instead of Strings and use the Hex format for constants (in fidl). In fdepl, hex literals are supported since milestone 0.11.1 (see #209). In fidl, it would provide more clarity to add a type alias:

```
typedef BitMask is UInt64
const BitMask message1 = 0x4711AFFE
```

A different solution could be to specify the registers or CAN messages as struct and add the number of bits for each struct element via fdepl. Actually, for this "BinaryProtocol" approach there is an example in the Franca repo, which models (a subset of) MQTT: https://github.com/franca/franca/blob/master/examples/org.franca.examples.deploy/models/org/example/deploy/MQTT3.fdepl

You find the fidl file for this and the (very simple) deployment specification if you follow the import paths in the example fdepl above.

What do you think about these two options?

**Comment by ck-euros** [comment]
I guess, I expected bit-related data definitions as a standard part of Franca, because I became used to it from structure definitions in C.
But changing my perpective and grasping Franca with the modelling mindset while taking into account different programming languages for implementation made it clear.
It really makes more sense to define bit-related properties in the deployment model.

Thank you very much for your suggestions. I chose to follow the "for struct_fields"-approach from the MQTT3 example.

Firstly, because options like
```
 Startbit: 7
```
and
``` 
 Bitlength: 11
```
are easier to verify than a bit mask equal to 0x0003FF80.

Secondly, it's easy to add further options, e.g.
```
 Endianess: {INTEL, MOTOROLA}  (optional)
```
or
```
 Signed: Boolean
```
.

**Comment by kbirken** [comment]
Good to hear that. It would be even possible to implement an external validator for deployment definitions, which checks that the Startbit/Bitlength combinations are consistent and issues error markers to the user in case of overlaps (or warnings in case of gaps). Here is an example of how to implement this kind of external validator: https://github.com/franca/franca/blob/master/examples/org.franca.examples.validators/src/org/franca/examples/validators/fdepl/SpecNameValidator.java

There is also a description of how to do this in section 11.1.2 of the user guide [published recently](https://drive.google.com/folderview?id=0B7JseVbR6jvhUnhLOUM5ZGxOOG8).
