### ISSUE TITLE
False Validation error for same names in different property hosts

### ISSUE THREAD

**Issue by GENIVIFRANCAPLUS** [franca/franca#256]
For the  given specification the 

```
package network

specification signal extends system.architecture {
	for attributes {
              MappedBusSignals : String [] ( optional ) ;
	}
	for arrays {
              MappedBusSignals : String [] ( optional ) ;
	}
}
```

the Franca Validator (V0.13.0) shows the error: 
Name conflict for property 'MappedBusSignals' due to conflicting property hosts (conflicting: arrays)

I cannot see, why this name conflict is a problem.

If I remove the validator org.franca.deploymodel.dsl.validation.FDeployValidatorAux.checkGroupArgumentType(Iterable<FDPropertyDecl>) then deploy generator generates code which is fine on the first sight.

**Comment by kbirken** [comment]
Here is the result of a first analysis.

1. The behavior seems to be the same for Franca deployment (fdepl) and component deployment (cdepl).

2. For the host `attributes`, the PropertyAccessor generator will create the following Java method:

```
public List<String> getMappedBusSignals(FAttribute obj) {
   return target.getStringArray(obj, "MappedBusSignals");
}
```

3. For the `arrays` host, the generator has to create one accessor method for each Franca element which might be of array type. This of course includes Franca attributes: `attribute UInt32[] someNiceIntArray`. 

4. Thus, the same method would be generated for the `arrays` host:
```
public List<String> getMappedBusSignals(FAttribute obj) {
   return target.getStringArray(obj, "MappedBusSignals");
}
```

5. Because the property types are the same (i.e. `String[]`) in this particular example, the generator could figure out that one of the two identical methods could be skipped in order to avoid a _duplicate method_ error from the Java compiler. However, we decided to not implement this because it is hard to figure out what are the correct methods in the general case.

6. If the property types were different, then there still would be a _duplicate method_ error, and the conflicting methods would have different return types (and we couldn't skip one of them, anyway). 

Hence, I think the validation error is correct - and we can close this issue. Comments?

**Comment by kbirken** [comment]
BTW: You mentioned that the generated code looks fine on first sight, did you actually did a Java syntax check or try to compile it? This should reveal the issue explained above...

**Comment by GENIVIFRANCAPLUS** [comment]
Klaus, thank you for explaining and you are right. It was only from the first sight. It wouldn't compile. 

There is some entropy in the naming of the generator methods, which leads to the problem. Perhaps the correct solution would be to include the host type into the generated name.

**Comment by kbirken** [comment]
You're right, there are some ambiguities due to the "collapsing" of method names. There is a trade-off between the simplicity of the PropertyAccessor API and the constraints on the property names imposed by this. I would be reluctant to change the generated API because of these ambiguities, but it might be worthwhile to include a configuration switch for the generator (and reduce the fdepl markers from error to warning). However, a switch like this adds complexity for downstream users, which is not necessarily a good thing. 

For now, I will close this issue because adding this generator configuration switch should be covered in a more specific issue (if we want to implement this at all).
